### ISSUE TITLE
style animate.css

### ISSUE THREAD

**Issue by charleshsb** [lewagon/rails-templates#107]
While deploying on heroku I add this issue : 
Refused to apply style from 'https://mr-portfolio.herokuapp.com/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I fixed it by changing from 

@import "animate.css/animate.css";
 to 
@import "animate.css/animate";

inside the application.scss file I noticed that the previous template was with @import "animate.css/animate";
and not 
@import "animate.css/animate.css";

**Comment by charleshsb** [comment]
I do not know if this is due to some update of rails or if this is an error in the template

**Comment by caioertai** [comment]
@charleshsb it's not a problem with the template. Heroku deals with assets differently and more than once I've had to fix deployments from students that were trying to load files using the `.css` extension in the path. Removing the extension worked every time. I'm not sure why tho.

**Comment by ssaunier** [comment]
Closing this, I checked the template uses the external repo `lewagon/rails-stylesheets` and we don't have explicit extensions there:

https://github.com/lewagon/rails-stylesheets/blob/master/application.scss
