### ISSUE TITLE
Add Css resseter

### ISSUE THREAD

**Issue by LyzioOh** [lewagon/rails-templates#11]
Hello, was thinking about adding a Css Resseter as my front-end teacher in aix-marseille told me it's a pretty common best practice.

If you are ok with that, will be happy clone and pull request.

**Comment by ssaunier** [comment]
Thanks for the suggestion @EEtancelin but it's [not necessary](http://stackoverflow.com/questions/19654568/is-it-necessary-to-add-reset-css-for-bootstrap-3)!
