### ISSUE TITLE
Add Stimulus

### ISSUE THREAD

**Issue by Eschults** [lewagon/rails-templates#134]
After the [Q3 2021 updates](https://lewagon-alumni.slack.com/archives/GC05UC8MV/p1626427512101400) which introduces more JavaScript in the curriculum, and especially promotes Stimulus as the recommended way to write JS in Rails, let's add Stimulus [setup steps](https://github.com/hotwired/stimulus-rails#installation) to the [Devise template](https://github.com/lewagon/rails-templates/blob/master/devise.rb) to let students focus on writing their controllers 🎉

**Comment by dmilon** [comment]
Fixed by [https://github.com/lewagon/rails-templates/commit/4625f999fd077756141b205e0671ad40bd2c5924}
