### ISSUE TITLE
Stimulus Rails 7

### ISSUE THREAD

**Issue by MarioCesarBais** [lewagon/rails-templates#140]
Error while generating new rails 7:
run  rails webpacker:install:stimulus from "."
rails aborted!
Don't know how to build task 'webpacker:install:stimulus' (See the list of available tasks with `rails --tasks`)

**Comment by ssaunier** [comment]
👋 Hello @MarioCesarBais, those templates are not yet ready for Rails 7, please make sure you use Rails 6 when you run `rails new` to use them for now. 

You can use this command to see which versions you have installed locally:

```bash
gem list | grep "^rails "
```

When you run `rails new ...` it will automatically pick up the latest one so uninstall any Rails 7+ version you might have:

```bash
gem uninstall rails
# This is an interactive command where you will be able to pick up which version you want to uninstall
```
