### ISSUE TITLE
[Idea] Use simple-form's fix for forms with radio_buttons

### ISSUE THREAD

**Issue by heismauri** [lewagon/rails-templates#142]
Hello there! I've noticed that the forms generated with this template make the first radio button align to the right. This is because bootstrap 5 requires something else. Luckily, simple_form's team have already fixed this [here](https://github.com/heartcombo/simple_form-bootstrap/blob/a130302e607c913fc7b578b3b180e40166218e32/app/assets/stylesheets/simple_form-bootstrap/_form_legend_clear.scss).

Here is an example:
W/O the `_form_legend_clear.scss` file
![without scss](https://i.imgur.com/d2UOa8F.png)

W the `_form_legend_clear.scss` file 
![with scss](https://i.imgur.com/GP10HIO.png)

I hope you can include this in your templates to make it easier for the people using your templates, myself included.

**Comment by dmilon** [comment]
Hello @heismauri :wave: 

We've just added the [_form_legend_clear.scss partial to our stylesheets](https://github.com/lewagon/rails-stylesheets/blob/master/components/_form_legend_clear.scss) which are imported when we create a new Rails app from one of our two templates.

Thank your for pointing this issue and coming with a solution :pray:
