### ISSUE TITLE
Devise template seems to have a problem with bootstrap import

### ISSUE THREAD

**Issue by SebastianPfeu** [lewagon/rails-templates#146]
After running the following commands I have received the error message below:

`rails new --database postgresql -m https://raw.githubusercontent.com/lewagon/rails-templates/master/devise.rb TEST_APP`

`cd TEST_APP`

`rails s`

<img width="1007" alt="Bildschirmfoto 2022-03-09 um 22 22 56" src="https://user-images.githubusercontent.com/67929127/157538443-7b54f016-2d9c-4555-b6be-3462b9ce3cf2.png">

**Comment by db0sch** [comment]
Thanks for reporting this issue @SebastianPfeu
Can you double check which version of Rails do you have (you can run `rails -v` in your terminal)

**Comment by SebastianPfeu** [comment]
Thanks for your response @db0sch 
I have Rails version 7.0.2.3 installed

**Comment by dmilon** [comment]
Hello @SebastianPfeu :wave: 

Thank you for your feedback :pray: 

Our Rails templates are not yet compatible with Rails 7. If you want to use them, we recommend you to uninstall Rails 7 and install Rails 6.1 before launching `rails new`. 

If you still want to use Rails 7, we have a [work in progress](https://github.com/lewagon/rails-templates/pulls) to adapt our templates to Rails 7 which should be released soon. Feel free to use this branch to create your app.
