### ISSUE TITLE
error: An error occurred while installing psych (5.1.0), and Bundler cannot continue.

### ISSUE THREAD

**Issue by cthonney** [lewagon/rails-templates#158]
If you encounter this error: 

> An error occurred while installing psych (5.1.0), and Bundler cannot continue.

**Run:**

Ubuntu/WSL
`sudo apt update`
`sudo apt install libyaml-dev`

MacOs 
`brew install libyaml
`

**Comment by max13h** [comment]
thank you !

**Comment by UtkarshDixit-97** [comment]
Thanks , got this in debian 12. Solved it.

**Comment by renatodeleao** [comment]
Thanks 🙏

**Comment by porag-m06** [comment]
What about windows 10/11?

**Comment by xrossinifonseca** [comment]
Thanks bro

**Comment by AZabalaZ** [comment]
gracias mi hermano, te recomiendo q veas PLM

**Comment by cedgeek** [comment]
This library is now included in the setup.
[https://github.com/lewagon/setup/pull/456]

**Comment by DeSoRka** [comment]
Thanks, it solved my problem

**Comment by ghost** [comment]
Thank you

**Comment by nataliaschlebinger** [comment]
Thank you so much! I got the same error on Lubuntu
