### ISSUE TITLE
GitHub flags a vulnerable package

### ISSUE THREAD

**Issue by guillaumecabanel** [lewagon/rails-templates#63]
The Boostrap gem is obsolete and has a vulnerability issue.
![image](https://user-images.githubusercontent.com/2414369/46740247-aa603480-cca2-11e8-9277-df8b1ce8a462.png)

Should be fixed with https://github.com/lewagon/teachers/issues/59

**Comment by mediter** [comment]
just tried to use this today,  the package.json still not updated

**Comment by ssaunier** [comment]
We are aware of this issue and are in the process of bumping the Wagon Curriculum to Bootstrap 4. Thanks for your patience.

In the meantime you can run:

```bash
yarn upgrade bootstrap@4.1.2
```
