### ISSUE TITLE
With divise.rb, when create new rails app, it stops here

### ISSUE THREAD

**Issue by hidehiro98** [lewagon/rails-templates#70]
With this command
```
rails new \
  --webpack \
  --database postgresql \
  -m https://raw.githubusercontent.com/lewagon/rails-templates/master/devise.rb \ 
  app_name
```

```
    generate  controller
Running via Spring preloader in process 58799
      create  app/controllers/pages_controller.rb
      invoke  erb
      create    app/views/pages
      create    app/views/pages/home.html.erb
       route  root to: 'pages#home'
         run  rm .gitignore from "."
      create  .gitignore
    generate  devise:install
```

**Comment by Eschults** [comment]
Hi @hidehiro98 thanks for reporting 🙏 
What's your `ruby -v`? `rails -v`?

**Comment by hidehiro98** [comment]
@Eschults Sure!
Rails version: 5.2.2
Ruby version: 2.5.3 (x86_64-darwin18)

**Comment by Eschults** [comment]
Hmm can't seem to reproduce your pb, did you try again several times, with a good internet connection? The logs shouldn't have stopped at `devise:install`, it's just a command that creates files and folders in your rails app. There's no error message before the command stops?

**Comment by hidehiro98** [comment]
@Eschults Thank you! I tried several times and works..
I'm still not sure but anyway it works.
