### ISSUE TITLE
Both Templates get stuck on generate simple_form:install Ubuntu 18.04

### ISSUE THREAD

**Issue by Loedn** [lewagon/rails-templates#73]
Last couple of lines from the terminal `Webpacker successfully installed 🎉 🍰
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
       rails  db:drop db:create db:migrate
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
Dropped database 'todo_development'
Dropped database 'todo_test'
Created database 'todo_development'
Created database 'todo_test'
    generate  simple_form:install`

and it sits there for atm 30mins

**Comment by Eschults** [comment]
Hi @Loedn thanks for reporting 🙏 

I can't reproduce your problem though:

<img width="504" alt="screenshot 2019-01-15 at 12 59 54" src="https://user-images.githubusercontent.com/8090140/51179356-7e69d600-18c5-11e9-9ac4-cae5678f4bac.png">


What's your OS / `ruby -v` / `rails -v`?

**Comment by Loedn** [comment]
Hi @Eschults 
OS `Ubuntu 18.04.1 LTS`
ruby -v `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
rails -v `Rails 5.2.2`
ask if any info is needed!

**Comment by Loedn** [comment]
![screenshot from 2019-01-15 15-12-00](https://user-images.githubusercontent.com/20359974/51185811-69e30900-18d8-11e9-80ad-b6fcb3e7c275.png)
this is the stacktrace when I interrupt the process

**Comment by Loedn** [comment]
solved by installing libsqlite3-dev with apt-get not sure why but work ¯\_(ツ)_/¯
