### ISSUE TITLE
Disable assets / helpers in generators

### ISSUE THREAD

**Issue by cveneziani** [lewagon/rails-templates#8]
How about adding this to `config/application.rb`?

```
config.generators do |g|
  g.assets = false
  g.helper = false
end
```

Extracted from [wagon_rails](https://github.com/lewagon/wagon_rails/issues/12) issues :grimacing:

**Comment by cveneziani** [comment]
What about helpers?

**Comment by ssaunier** [comment]
As I said in the commit message, we keep them.

**Comment by cveneziani** [comment]
Yep, I saw the commit message. I was just wondering why.
It's always annoying to debug the apps of the students when they have a lot of empty generated helper files.
