### ISSUE TITLE
gitignore doesn't include master.key

### ISSUE THREAD

**Issue by connorshea** [lewagon/rails-templates#83]
`config/master.key` is ignored by the default Rails `.gitignore` in Rails 5.2 and 6.0. This template doesn't include that file in the ignore, so a lot of people who have used this template have pushed their master keys up to GitHub. (See more info on encrypted credentials [here](https://www.engineyard.com/blog/rails-encrypted-credentials-on-rails-5.2))

The gitignore should be updated to include these two lines:

```gitignore
# Ignore master key for decrypting credentials and more.
/config/master.key
```

https://github.com/lewagon/rails-templates/blob/89b7f3bb74ae4aed812018b2f355dfc16294acd5/clever_cloud/minimal.rb#L159

Or, even better it should just append whatever custom ignores you need to the default `.gitignore` so problems like this don't need to be fixed with every new Rails release.

Thanks :)

**Comment by ssaunier** [comment]
It's serious indeed, thank you @connorshea for the report. @db0sch will look at this ASAP, my intuition is that we can remove this line from the template and use the default Rails `.gitignore` file now.

We used to use the [figaro](https://github.com/laserlemon/figaro) gem so that we added `config/application.yml`. 

I just generated a `rails new` with Rails 6.0 and this is what we get:

```bash
# See https://help.github.com/articles/ignoring-files for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore all logfiles and tempfiles.
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

# Ignore uploaded files in development.
/storage/*
!/storage/.keep

/public/assets
.byebug_history

# Ignore master key for decrypting credentials and more.
/config/master.key

/public/packs
/public/packs-test
/node_modules
/yarn-error.log
yarn-debug.log*
.yarn-integrity
```

We might need to append `.env` and call it a day.

@db0sch I'll let you pursue the investigation, thanks 🙏

**Comment by db0sch** [comment]
@ssaunier @connorshea 
Just created this PR #84  that will append some of our custom ignores (mainly `.env` and some OS related files types).

Thank you very much @connorshea 🙏 for your help on this serious issue.

**Comment by connorshea** [comment]
@ssaunier @db0sch thanks for the quick reaction on this! :)
