### ISSUE TITLE
Webpacker Conflict With Mapbox-GL

### ISSUE THREAD

**Issue by metalogica** [lewagon/rails-templates#87]
During AirBnB project week at batch 329 in Montreal we had a Mapbox-GL issue with one group.

Image of error attached below.

The solution was to downgrade Webpacker to v.3.5.5 in the Gemfile.

This might be a problem for other groups in other batches so I thought I'd point it out. If not, then please ignore and close the issue 👍 

![](https://res.cloudinary.com/dtmuylvrr/image/upload/v1574446827/Screenshot_2019-11-22_at_12.07.21.png)

**Comment by dmilon** [comment]
The bug was not reported for a long time and should have been fixed since. I'm closing.
