### ISSUE TITLE
Rails Templates Minimal & Devise are not running pgrep spring | xargs

### ISSUE THREAD

**Issue by liberom** [lewagon/rails-templates#95]
While trying to install both templates, the installation stops after this:
```
        apply  https://raw.githubusercontent.com/lewagon/rails-templates/master/minimal.rb
         run    pgrep spring | xargs kill -9 from "."

Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
```

**Comment by AntoineMassoni** [comment]
I have the same problem...

**Comment by liberom** [comment]
@ssaunier not sure who to ping

**Comment by Eschults** [comment]
Hello @liberom thanks for reporting 🙏 
On which OS are you? Which version?

**Comment by benjyarel** [comment]
Hello @Eschults !
A friend had the same problem last week, she uses Ubuntu . ( ruby : 2.6.3 and rails : 5.2.4)
It works for me, and I am on Mac OS.

**Comment by liberom** [comment]
Hello Edward!
I’m using Ubuntu 18.x



Sent from myMail for iOS


Tuesday, 21 January 2020 05:52 -0300 from notifications@github.com  <notifications@github.com>:
